version: '3.4'

services:
  scheduler:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: development
      DOMAIN: http://127.0.0.1:3000/
    ports:
      - 3000:3000
    command: sh -c "npm install --silent && sleep 10 && npm start "
